### PR TITLE
use pkg_config before have_library

### PR DESCRIPTION
**Pull request by znz**
This will fix error with ImageMagick 6.8.0 Q16.

### CODE REVIEW

**Comment by silasrnc** [comment]
:+1:

**Comment by ncopa** [comment]
Can you please tag a new release? It is a pain for us distro maintainers to patch those gem files...

**Comment by ept** [comment]
Recent Homebrew (Mac OS X) installations require this fix in order for rmagick to be installed. Could we get this merged into a new release please?

**Comment by barthalion** [comment]
Any up-to-date distribution requires this change. Could you make new release?

**Comment by mereghost** [comment]
This is critical to a lot of folks using RMagick in dev and production environments, so a :+1:  is more than justified.

Can you guys release an update asap?

**Comment by mmaiza** [comment]
This is now fixed in the new release.

**Comment by ept** [comment]
@mmaiza Thank you!

**Pull request closed without merging**
