### PR TITLE
New imagemagick library names

### PR DESCRIPTION
**Pull request by jo**
Magick++-Q16 e.g. on Arch-Linux

### CODE REVIEW

**Comment by skalee** [comment]
Fixes https://github.com/rmagick/rmagick/issues/60 as well (and probably more), please merge.

**Comment by caarlos0** [comment]
Can someone please merge this?

**Comment by ncopa** [comment]
Wouldnt it be better to use pkg-config for this instead? See issue #62

**Comment by rmagick-temp** [comment]
Sorry I could not get to this faster. I will be putting together a new release in the next few days. I cannot just use the pulls as they are I want a solution that will work better for future releases.

Moncef

**Comment by mmaiza** [comment]
This is now fixed in newest release

**Pull request closed without merging**
