### PR TITLE
Fix the bug for MSWIN and MINGW

### PR DESCRIPTION
**Pull request by dw3w4at**
Edit the code for checking ImageMagick version from `convert -version` to `identify -version`.
Because there is already existing convert command for windows file system utility.

### CODE REVIEW

**Comment by dicom** [comment]
I've also experienced this conflict on windows.
+1 for such a change.

BTW, this simple commit has actually been sitting here uncommented for half a year.
Surprising that such a popular gem get's such a low level of attention.

**Comment by wingfire** [comment]
+1
YES PULL IT 111elf!!!

**Comment by dw3w4at** [comment]
This is the issue as known as "convert Issue"
http://www.imagemagick.org/Usage/windows/#convert_issue

**Comment by wingfire** [comment]
Hi,
reinstalled the stuff with windows 7 64bit today again.
It's working fine with ImageMagick-6.7.6-1-Q16-windows-dll.exe.
You can close the ticket.

HINT: Restart your cmd prompt after installing ImageMagick and before installing rmagick.

**Comment by dw3w4at** [comment]
OK, I see.

**Pull request closed without merging**
