### PR TITLE
Fix installation error on systems with HRDI enabled RMagick

### PR DESCRIPTION
**Pull request by peteonrails**
Integrates @bricef's fork, which in-turn implements a widely-available and widely-tested patch for HDRI enabled RMagick. 

Most linux package maintainers are moving toward HDRI support. The pull request makes RMagick usable on those systems. 

More details in #18

### CODE REVIEW

**Comment by mmaiza** [comment]
I will merge this but I will not build a gem yet since there no tests. I will first make sure that all the tests run

**Comment by anatol** [comment]
When can we expect a new version of rmagick? Current bug does not allow me to install the *.gem file.

**Comment by jneen** [comment]
@anatol as a workaround, you can clone the repo and run

``` sh
$ gem build rmagick.gemspec
$ gem install ./rmagic-*.gem
```

**Comment by gagalago** [comment]
What kind of test is expected to be implemented ?

**Pull request merged**
